# Generated by Django 4.2.2 on 2023-07-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=50)),
                ('release_date', models.DateTimeField()),
                ('lte_exists', models.BooleanField(default=False)),
            ],
        ),
    ]
